descriptor-schema-version: "2.2"
info:
  name: iox-ir1101-dio-rw
  version: latest
  description: Set Cisco IR1101 Digital IO using a Web interface (Apache, Python, jQuery, Ajax)
  author-name: Emmanuel Tychon <etychon@cisco.com>
app:
  cpuarch: aarch64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    profile: custom
    cpu: "200"
    memory: "128"
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "8080"
    devices:
      -
        label: DIO_1
        type: serial
        usage: "GPIO Port 1"
      -
        label: DIO_2
        type: serial
        usage: "GPIO Port 2"
      -
        label: DIO_3
        type: serial
        usage: "GPIO Port 3"
      -
        label: DIO_4
        type: serial
        usage: "GPIO Port 4"
  startup:
    rootfs: rootfs.tar
    target:
    - sh
    - /start.sh
  type: docker
